image: edbizarro/bitbucket-pipelines-php7

pipelines:
  branches:
    staging:
      - step:
          caches:
            - node
          script:
            - yarn install
            - yarn lint
            - yarn prod
            - yarn rsync:staging
          deployment: staging
    master:
      - step:
          caches:
            - node
          script:
            - yarn install
            - yarn lint
            - yarn prod
            - yarn rsync:production
          deployment: production